name: nehing_generator
description: 의미 없는 랜덤 한글 문자열을 생성하는 녜힁 제조기
version: 0.0.1
repository: https://github.com/highgw/nehing_generator
homepage: https://github.com/highgw/nehing_generator
license: MIT

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
