name: nehing_generator
description: >
  A Dart package that generates meaningless but funny random Korean text
  (known as 'Nehing') for dummy content, testing, games, and fun experiments.
version: 0.0.3
repository: https://github.com/highgw/nehing_generator
homepage: https://github.com/highgw/nehing_generator
license: MIT

environment:
  sdk: ">=2.17.0 <4.0.0"

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
